DSL2: add reference masking for PMDtools
nf-core/eager pull request #1030
Opened 2023-10-27 10:55 UTC by scarlhoff

This adds the options to run PMDtools only on a specific part of the genome within the damage manipulation subworkflow. Input options are the mapping reference, an already masked fasta file and a bed file for masking of the mapping reference.
This closes #1029.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](<https://github.com/>nf-core/eager/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/eager _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-11-10 15:11 UTC, jfy133 approved these changes
From my phone so not tested, but theoretically looks good :)

2023-11-10 15:11 UTC, jfy133 commented on docs/output.md
> +  - `*.masked.fa`: _Only present if a BED file has been supplied with `--damage_manipulation_pmdtools_reference_mask` or within a reference sheet._ Reference FASTA file with positions from the BED fi
See comment above about most suitable place

2023-11-16 08:01 UTC, TCLamnidis requested changes

2023-12-05 15:57 UTC, TCLamnidis approved these changes
One minor helptext suggestion, but otherwise LGTM!

2023-12-08 09:20 UTC, merged