dsl2: metagenomics uncollapsed paired end
nf-core/eager pull request #1098
Opened 2024-11-15 11:16 UTC by ilight1542

Draft PR for metagenomics paired-end merging off.

This is a QOL improvement for tools that can use paired end information (kraken2, krakenuniq), and now allows for variable inputs into these tools (by splitting inputs into either PE or SE data and running separate instances).

Main issues resolved:
- input parsing for paired-end compatible tools (kraken2, krakenuniq, metaphlan) added when `--preprocessing_skippairmerging` used.
- Mixed paired end/single end data parses OK and outputs are properly saved
- Warning for users that singletons are not assessed when skipping pairmerging. and metaphlan, which does not use paired end information should likely not be used with this parameter.

TODOs:
- for metagenomics generally - check that behavior of mapped/all is distinct, ensure that samtools.fastq.out.other is distinct for these two modes
- possibly merge all reads back to a single file for `--metagenomic_input all`

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](<https://github.com/>nf-core/eager/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/eager _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2025-02-21 11:35 UTC, ilight1542 commented on conf/modules.config
> +        tag = { ${meta.single_end} ? "single_end" : "paried_end" }
does not correctly parse meta.single_end despite working within the module itself...

2025-02-28 10:14 UTC, ilight1542 commented
Ready for review:

Basic Overview: We can now retain PE information from unmerged input fastq files (when `--preprocessing_skippairmering` is set).

PE samples going into metagenomics will be separately input into metaphlan, kraken2, and krakenuniq. Malt does not accept PE reads so it is not allowed with the param combo.

Also fixed a small error in the parsing of metagenomics input data from bamfiltering --> metagnomics.

2025-02-28 11:37 UTC, merszym requested changes
Based on visual inspection, it looks good to me!

I would remove the one map-channel manipulation in metagenomics (see comment) as it is not necessary anymore 

Also I have not tested anything, so I trust your tests for now :P

2025-02-28 11:37 UTC, merszym commented on subworkflows/local/bamfiltering.nf
>      } else if ( ( params.run_metagenomics && ( params.metagenomics_input == 'mapped' || params.metagenomics_input == 'all' ) ) && params.preprocessing_skippairmerging ) {
if input now is 'all', the unmapped reads are not taken into account.

I think that needs one more if-condition, with something like 
if metagenomics_input == 'all':
CAT_FASTQ_MAPPED.out.reads.mix(CAT_FASTQ_UNMAPPED.out.reads).mix(ch_paired_fastq_for_cat)

but I might miss something here?

2025-02-28 11:37 UTC, merszym commented on subworkflows/local/bamfiltering.nf
>      } else if ( ( params.run_metagenomics && ( params.metagenomics_input == 'mapped' || params.metagenomics_input == 'all' ) ) && params.preprocessing_skippairmerging ) {
It looks like the unmapped reads are not filtered out? then it makes sense...

2025-02-28 11:37 UTC, merszym commented on docs/development/metagenomics_paired_end.md
> +ISSUE FOUND: while the outputting of PE reads is OK in bamfiltering.nf (fastq_mapped & fastq_unmapped) when overlap merging is not done cat_fastq weirdly merges singletons to one PE file and other to
That sounds like a hackathon-thing to do

2025-02-28 11:37 UTC, merszym commented on subworkflows/local/metagenomics_profiling.nf
>                  [
if the meta already contains the informatino, this whole map can go away. I created this map only to add the 'single_end' back to the meta

2025-02-28 11:37 UTC, merszym commented on subworkflows/local/utils_nfcore_eager_pipeline/main.nf
> -        .groupTuple()
just to make sure - this was the weird input-validation that did nothing and randomly failed?

2025-03-07 09:14 UTC, ilight1542 commented on docs/development/metagenomics_paired_end.md
> +ISSUE FOUND: while the outputting of PE reads is OK in bamfiltering.nf (fastq_mapped & fastq_unmapped) when overlap merging is not done cat_fastq weirdly merges singletons to one PE file and other to
let me double check this behavior and add more context of what we might need to do in a hackathon... i this was more for my own notes reference but was not edited prior to opening the PR.

2025-03-07 09:29 UTC, ilight1542 commented on subworkflows/local/metagenomics_profiling.nf
>                  [
but we do want to have 2 groups of files for input into krakenuniq (which runs all samples in a single execution): one single_end group and one paired end group. Therefore for groupTuple() we need to have a new meta-like field (not in meta explicitly) that keeps just the SE vs PE info -> sort

2025-03-07 09:42 UTC, ilight1542 commented on subworkflows/local/bamfiltering.nf
>      } else if ( ( params.run_metagenomics && ( params.metagenomics_input == 'mapped' || params.metagenomics_input == 'all' ) ) && params.preprocessing_skippairmerging ) {
the splitting of all vs only mapped reads is dealt with at the modules.config level. 

`    withName: SAMTOOLS_FASTQ_MAPPED {
        tag = { "${meta.reference}|${meta.sample_id}_${meta.library_id}" }
        ext.args = [
            params.metagenomics_input == 'all' ? '' : '-F 4',
`

We could split the module/import into an additional SAMTOOLS_FASTQ_ALL, for clarity for anyone looking into this section of the pipeline... @jfy133 what are your thoughts?

2025-03-07 11:11 UTC, ilight1542 commented on subworkflows/local/bamfiltering.nf
>      } else if ( ( params.run_metagenomics && ( params.metagenomics_input == 'mapped' || params.metagenomics_input == 'all' ) ) && params.preprocessing_skippairmerging ) {
I adjusted this whole section to imporve clarity. please see latest commit.

essentially the splitting of the fastq and cat into unmapped and mapped versions is unnecessary. all parameters can be parsed fine within modules config.

i confirmed that the md5sum of the final files sent to the ch_fastq_for_metagenomics channel are consistent across all the parameter combos that we were there.

2025-03-07 11:18 UTC, ilight1542 commented on subworkflows/local/bamfiltering.nf
> +    //    All bam -> fastq filtering options (-F 4, -f 4 or none) will be dealt with within modules.config
@TCLamnidis please take a quick look -- i restructured everything into a single call, since the modules.config is easily robust enough to deal with the splitting. and it allows for much cleaner code in this section which should help going forward

2025-03-12 09:26 UTC, ilight1542 commented on subworkflows/local/bamfiltering.nf
> +    //    All bam -> fastq filtering options (-F 4, -f 4 or none) will be dealt with within modules.config
or @jfy133 who i think wrote the initial implementation...

2025-03-14 08:30 UTC, merszym commented on subworkflows/local/metagenomics_profiling.nf
>                  [
Ah, I see. Alright, then this makes sense :)

2025-03-14 09:14 UTC, merszym commented on subworkflows/local/bamfiltering.nf
> +    //    All bam -> fastq filtering options (-F 4, -f 4 or none) will be dealt with within modules.config
I think that makes it much easier! Nice one :)

2025-03-14 09:16 UTC, merszym approved these changes

2025-03-21 10:59 UTC, merged