General Doc Improvements
nf-core/eager pull request #566
Opened 2020-09-29 14:45 UTC by jfy133

# nf-core/eager pull request

This is to close #553 and close #554 and close #555 

General clarifications to various aspects, but primarily adding reference to which nf-core/eager parameter refers to which specific tool parameter at the request from @ashildv

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If necessary, also make a PR on the [nf-core/eager branch on the nf-core/test-datasets repo](https://github.com/nf-core/test-datasets/pull/new/nf-core/eager)
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --paired_end`).
- [ ] Make sure your code lints ([`nf-core lint .`](https://nf-co.re/tools)).
- [x] Documentation in `docs` is updated
- [x] `CHANGELOG.md` is updated
- [x] `README.md` is updated

**Learn more about contributing:** [CONTRIBUTING.md](https://github.com/nf-core/eager/tree/master/.github/CONTRIBUTING.md)

2020-10-06 12:20 UTC, apeltzer commented on README.md
> +* **DamageProfiler** Neukamm, J., Peltzer, A., & Nieselt, K. (2020). DamageProfiler: Fast damage pattern calculation for ancient DNA. In bioXiv (p. 2020.10.01.322206). https://doi.org/10.1101/2020.10
```suggestion
* **DamageProfiler** Neukamm, J., Peltzer, A., & Nieselt, K. (2020). DamageProfiler: Fast damage pattern calculation for ancient DNA. In biorXiv (p. 2020.10.01.322206). https://doi.org/10.1101/2020.10.01.322206 Download: [https://github.com/Integrative-Transcriptomics/DamageProfiler](https://github.com/Integrative-Transcriptomics/DamageProfiler)
```

2020-10-06 13:42 UTC, TCLamnidis commented on docs/output.md
> +In the case of dual-indexed paired-end sequencing, it is likely poly-G tails are less of an issue as during your adapterRemoval step, anything passed the adapter will be clipped off anyway. However y
```suggestion
In the case of dual-indexed paired-end sequencing, it is likely poly-G tails are less of an issue as during your AdapterRemoval step, anything passed the adapter will be clipped off anyway. However you can check this under the 'Per Sequence GC Content' plot in FastQC.
```

2020-10-06 14:11 UTC, TCLamnidis commented on main.nf
> +            if (!seqtype.matches('PE') && !seqtype.matches('SE')) exit 1, "[nf-core/eager] error:  SeqType for one or more rows in TSV is neither SE nor PE! see --help or documentation under 'running
```suggestion
            if (!seqtype.matches('PE') && !seqtype.matches('SE')) exit 1, "[nf-core/eager] error:  SeqType for one or more rows in TSV is neither SE nor PE! see --help or documentation under 'running the pipeline' for more information. You have: '${seqtype}'"
```

2020-10-06 14:16 UTC, TCLamnidis commented on docs/usage.md
> +can only be used on paired-end data! :warning: If you run this and also with
```suggestion
can only be used on paired-end data! :warning: If you provide this option together with
```

2020-10-06 14:16 UTC, TCLamnidis commented on docs/usage.md
> +Defineshow many mismatches from the reference are allowed in a read. By default
```suggestion
Defines how many mismatches from the reference are allowed in a read. By default
```

2020-10-06 14:19 UTC, TCLamnidis commented on docs/usage.md
> +killed by a user (e.g. using ctrl + z to hard kill an crashed run).
```suggestion
killed by a user (e.g. using ctrl + z to hard kill a crashed run).
```

2020-10-06 14:20 UTC, TCLamnidis commented on docs/usage.md
> +> :warning: this tutorial does not describe how to install and set-up
```suggestion
> :warning: this tutorial does not describe how to install and set up
```

2020-10-06 14:22 UTC, TCLamnidis commented on docs/usage.md
> +> :warning: this tutorial does not describe how to install and set-up
```suggestion
> :warning: this tutorial does not describe how to install and set up
```

2020-10-06 19:53 UTC, apeltzer commented
Merged all your review points @TCLamnidis - should be good now mostly :-)

2020-10-07 06:22 UTC, jfy133 commented on docs/usage.md
> +<...>
```suggestion
```

2020-10-07 17:23 UTC, aidaanva commented on docs/output.md
>  It is useful when you do not have large computing power or you want very rapid and want rough approximation of the metagenomic profile of your sample.
repetition of want

2020-10-07 17:25 UTC, aidaanva commented on docs/output.md
> +This plot shows the distribution of th frequency of reads at different GC contents. The X axis represents the GC content (i.e the percentage of Gs and Cs nucleotides in a given read), the Y axis repr
is "th" meant to be the?

2020-10-07 17:32 UTC, aidaanva commented on docs/output.md
> +If you ran with `--min_allele_freq_hom` and `--min_allele_freq_het` set to two different values (left panel A in the figure below), this allows you to assess the number of multi-allelic positions tha
I don't think I understand what "smallish on haploid genomes"... what does that mean? multiple possible 'alleles' can also suggest multiple strains being present. The shape of the plot (do we have any plot being produced???) can give you an indication of that

2020-10-07 17:38 UTC, aidaanva commented on docs/output.md
>  It is useful when you do not have large computing power or you want very rapid and want rough approximation of the metagenomic profile of your sample.
```suggestion
It is useful when you do not have large computing power or you want very rapid and rough approximation of the metagenomic profile of your sample.
```

2020-10-07 17:38 UTC, aidaanva commented on docs/output.md
> +This plot shows the distribution of th frequency of reads at different GC contents. The X axis represents the GC content (i.e the percentage of Gs and Cs nucleotides in a given read), the Y axis repr
```suggestion
This plot shows the distribution of the frequency of reads at different GC contents. The X axis represents the GC content (i.e the percentage of Gs and Cs nucleotides in a given read), the Y axis represents a frequency.
```

2020-10-07 17:44 UTC, aidaanva commented on docs/usage.md
> +7. For input BAM files  you should provide small decoy reference genome with
```suggestion
7. For input BAM files you should provide small decoy reference genome with
```

2020-10-07 17:47 UTC, aidaanva commented on docs/usage.md
> +  - If you _regularly_ want to run the situation above, please leave an feature
```suggestion
  - If you _regularly_ want to run the situation above, please leave a feature
```

2020-10-07 17:51 UTC, aidaanva commented on docs/usage.md
> +supplying BAM files). You should small decoy reference genome with pre-made
```suggestion
supplying BAM files). You should use a small decoy reference genome with pre-made
```

2020-10-07 19:07 UTC, aidaanva requested changes
Left some comments for stuff that should be changed

2020-10-07 19:07 UTC, aidaanva commented on docs/usage.md
> +  you have recieved enough coverage for downstream, and/or do you lose an
```suggestion
  you have received enough coverage for downstream, and/or do you lose an
```

2020-10-07 19:07 UTC, aidaanva commented on docs/usage.md
> +  complexity).
Add warning that for captured libraries the cluster factor may be higher just because of the enrichment of the library

2020-10-07 19:07 UTC, aidaanva commented on docs/usage.md
> +  covered indicating you have the right reference genome?
Also that the decrease between the different % of the genome covered is gradual and not drastic

2020-10-07 19:07 UTC, aidaanva commented on docs/usage.md
> +output files that can be used for downstream analysis.
Want to add a warning that this showcases the functionality of the pipeline, but the shown parameters/settings are not the ones which are normally used, like you would not want to have het calls in your SNP alignment for phylogenetic inference.

2020-10-08 11:00 UTC, apeltzer approved these changes

2020-10-08 11:11 UTC, merged