added default -doMajorMinor 1 to output angsd beagle format
nf-core/eager pull request #690
Opened 2021-03-08 17:18 UTC by alexandregilardet

+ corrected typo in error message about angsd output format

To output ANGSD beagle format, the argument -doMajorMinor to infer major and minor alleles is required. For now, eager would output a corrupted .glf.gz file if 'beagle' is selected as output with the following .command.err:
-> For dumping beaglestyle output you need to estimate major/minor: -doMajorMinor
I added as default the -doMajorMinor 1 argument which I'm more familiar with (http://www.popgen.dk/angsd/index.php/Major_Minor).

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] Make sure your code lints (`nf-core lint .`).
- [x] Ensure the test suite passes (`nextflow run . -profile test_tsv,crick`).

2021-03-08 18:41 UTC, apeltzer commented
You will need to add this change to the `CHANGELOG.md` too to make the tests pass 👍🏻

2021-03-09 10:18 UTC, alexandregilardet commented
Ok I THINK I got it right now...

2021-03-09 20:13 UTC, jfy133 requested changes
Good catch on the typos in the validation section.

There was a mistake in the changelog I think, but otherwise I think we are good to go.

2021-03-09 20:13 UTC, jfy133 commented on CHANGELOG.md
> -- [679](https://github.com/nf-core/eager/issues/679) - Refactor within-process bash conditions to groovy/nextflow, due to incompatibility with some servers environments
Was this all meant to be deleted? Your change should just be appened to the endof the list.

2021-03-10 10:15 UTC, jfy133 approved these changes

2021-03-10 10:15 UTC, jfy133 commented
Looks good to me! Merging!

2021-03-10 10:16 UTC, jfy133 commented
Thanks very much @alexandregilardet ! Feel free to make an extra PR adding yourself to the `contributors` list on the main README if you're happy to do so :)

2021-03-10 10:16 UTC, merged