Add Falco as an alternative to FastQC
nf-core/eager pull request #949
Opened 2023-03-03 10:12 UTC by scarlhoff

closes #947

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
    - [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](<https://github.com/>nf-core/eager/tree/master/.github/CONTRIBUTING.md)
    - [x] If necessary, also make a PR on the nf-core/eager _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint .`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

2023-03-03 10:14 UTC, scarlhoff commented
@nf-core-bot fix linting

2023-03-10 08:28 UTC, jfy133 requested changes
Very minor documentation tweaks but otherwise LGTM

2023-03-10 08:28 UTC, jfy133 commented on docs/output.md
> +Falco results in the `raw/` directory contain the results of running Falco on the 'raw' input files (with no processing by the pipeline). The `processed/` directory is for reads run through either fa
```suggestion
Falco results in the `raw/` directory contain the results of running Falco on the 'raw' input files (with no processing by the pipeline). The `processed/` directory is for reads run through either fastp or AdapterRemoval preprocessing, and therefore will only be present if preprocessing is executed. These Falco results occur in both .html (the report) and .txt format (raw data), and should provide the  same information as with FastQC.
```

2023-03-10 08:28 UTC, jfy133 commented on nextflow_schema.json
> +                    "help_text": "Sets the duplicate read removal tool. By default uses `markduplicates` from Picard. Alternatively an ancient DNA specific read deduplication tool `dedup` (Peltzer et
```suggestion
                    "help_text": "Sets the duplicate read removal tool. By default uses `markduplicates` from Picard. Alternatively an ancient DNA specific read deduplication tool `dedup` (Peltzer et al. 2016) is offered. The latter utilises both ends of paired-end data to remove duplicates (i.e. true exact duplicates, as markduplicates will over-zealously deduplicate anything with the same starting position even if the ends are different).\n\n> ⚠️ DeDup can only be used on collapsed (i.e. merged) reads from paired-end sequencing.",
```

2023-03-10 09:03 UTC, jfy133 approved these changes
Just remembered you are on excavation so I've committed my suggestions and will merge in already :)

2023-03-22 08:08 UTC, jfy133 commented
@nf-core-bot fix linting

2023-03-22 09:11 UTC, merged