Adding endorspy
nf-core/eager pull request #961
Opened 2023-03-28 09:45 UTC by aidaanva

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](<https://github.com/>nf-core/eager/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/eager _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-03-28 10:08 UTC, jbv2 approved these changes

2023-03-28 14:07 UTC, jfy133 requested changes
Missing `citations.md` update (either with zenodo or eager2)

2023-03-28 15:12 UTC, TCLamnidis requested changes

2023-03-28 15:12 UTC, TCLamnidis commented on subworkflows/local/endorspy.nf
> +//outputs for the flagstats will look like:     tuple val(meta), path("*.flagstat"), emit: flagstat
Harshil align

2023-03-28 15:12 UTC, TCLamnidis commented on subworkflows/local/endorspy.nf
> +    if ( params.run_bamfiltering & !params.skip_deduplication ) {
```suggestion
    if ( params.run_bamfiltering && !params.skip_deduplication ) {
```

2023-03-28 15:12 UTC, TCLamnidis commented on subworkflows/local/endorspy.nf
> +    } else if ( !params.run_bamfiltering & !params.skip_deduplication) {
```suggestion
    } else if ( !params.run_bamfiltering && !params.skip_deduplication) {
```

2023-03-28 15:12 UTC, TCLamnidis commented on workflows/eager.nf
> +    // ENDORSPY (raw, filtered, deduplicated)
```suggestion
    // ENDORSPY (raw, filtered, deduplicated)
    //
    
```

2023-03-29 09:44 UTC, jfy133 commented on subworkflows/local/endorspy.nf
> +//outputs for the flagstats will look like:     tuple val(meta), path("*.flagstat"), emit: flagstat
tm™️

2023-03-29 09:47 UTC, jfy133 reviewed
- Missing version mixing

2023-03-29 09:47 UTC, jfy133 commented on subworkflows/local/endorspy.nf
> +                                                .join (flagstats_duplicated)
```suggestion
        ch_for_endorspy_complete = flagstats_raw
                                                                 .join (flagstats_filtered)
                                                                 .join (flagstats_duplicated)
```

2023-03-29 09:47 UTC, jfy133 commented on subworkflows/local/endorspy.nf
> +                                                            }
```suggestion
                                                        .map {
                                                            meta, flags_raw, flags_filtered ->
                                                            [ meta, flags_raw, flags_filtered, [] ]
                                                        }
```

And in all others

2023-03-29 12:42 UTC, jfy133 approved these changes
Nice refactoring!

2023-03-29 12:42 UTC, jfy133 commented on workflows/eager.nf
> +
```suggestion
                                    .join(ch_for_endorspy_dedupped.ifEmpty([ [], [] ]))
                                    
    ENDORSPY ( ch_for_endorspy )
```

2023-03-29 12:42 UTC, jfy133 commented on workflows/eager.nf
> +
```suggestion
```

2023-03-29 12:42 UTC, jfy133 commented on workflows/eager.nf
> +
```suggestion
```

2023-03-29 15:00 UTC, TCLamnidis requested changes

2023-03-29 15:00 UTC, TCLamnidis commented on workflows/eager.nf
> +    ch_multiqc_files  = ch_multiqc_files.mix( ENDORSPY.out.json )
Harshil Align

2023-06-16 13:26 UTC, aidaanva commented
@nf-core bot fix linting

2023-06-16 13:56 UTC, TCLamnidis commented
@nf-core-bot fix linting

2023-06-30 12:02 UTC, TCLamnidis requested changes
- [ ] Minor changes to `output.md`.

- [x] Minor changes to channel operator formatting in `eager.nf`

- [ ] Please check `modules.conf`. It seems the     `withName: 'SAMTOOLS_INDEX_MEM|SAMTOOLS_INDEX_BT2' {` block has been duplicated (probably due to a merge conflict resolve?). Please ensure module configurations are in the correct "category block" and remove the superfluous config block for `SAMTOOLS_INDEX_MEM|SAMTOOLS_INDEX_BT2`
- [x] There seems to be a superfluous `ENDORSPY.out.json` in `eager.nf`. Does that do something? if not, remove it.

2023-07-07 09:25 UTC, TCLamnidis approved these changes
Minor tweaks. Added a future TODO.
Otherwise LGTM!

2023-07-07 09:25 UTC, TCLamnidis commented on conf/modules.config
> +
```suggestion
```

2023-07-07 09:25 UTC, TCLamnidis commented on conf/modules.config
> +        tag = { "${meta.reference}|${meta.sample_id}_${meta.library_id}_L${meta.lane}" }
```suggestion
        // TODO Once a lane-merging step is added for input BAMs, the lane should be dropped from this tag.
        tag = { "${meta.reference}|${meta.sample_id}_${meta.library_id}_L${meta.lane}" }
```

2023-07-07 09:25 UTC, TCLamnidis commented on docs/output.md
> +$$ Percent_Duplicates = {(TotalReadsPreDedup - MappedReadsDedup) \over TotalReadsPreDedup \* 100} $$
```suggestion
$$ PercentDuplicates = {(TotalReadsPreDedup - MappedReadsDedup) \over TotalReadsPreDedup \* 100} $$
```

2023-07-10 08:31 UTC, merged